# Generated by Django 5.1.2 on 2025-01-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntry', '0002_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
