# Generated by Django 5.1.2 on 2025-01-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntry', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='countery',
            new_name='country',
        ),
    ]
