# Generated by Django 5.1.2 on 2025-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntry', '0004_rename_countery_customer_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=10, max_digits=10)),
                ('retirement', models.DecimalField(decimal_places=10, max_digits=10)),
                ('other_benefits', models.DecimalField(decimal_places=10, max_digits=10)),
                ('total_benefits', models.DecimalField(decimal_places=10, max_digits=10)),
                ('total_compensation', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
