# Generated by Django 5.1.2 on 2025-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uplodes/')),
                ('model_name', models.CharField(max_length=200)),
                ('uploded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
